drop database if exists bdfarmacia;
create database bdfarmacia;
use bdfarmacia;

create table ENFERMOS (
CODIGO_E INT auto_increment PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
DIRE VARCHAR(100) NOT NULL,
UNIQUE UPPER(NOME)
);

create table FARMACOS (
CODF INT NOT NULL PRIMARY KEY,
NOMF VARCHAR(40) NOT NULL,
PRECIOUNIDAD VARCHAR(4) NOT NULL CHECK (PRECIOUNIDAD >= 0)
);

create table CONSUMO (
UNIDADES INT NOT NULL CHECK (UNIDADES > 0),
CODIGO_E INT AUTO_INCREMENT,
CODF INT NOT NULL,
FOREIGN KEY (CODIGO_E) REFERENCES ENFERMOS(CODIGO_E) ON DELETE RESTRICT ON UPDATE CASCADE,
FOREIGN KEY (CODF) REFERENCES FARMACOS(CODF) ON DELETE CASCADE ON UPDATE CASCADE
);

create table TIPOFARMACO (
TIPOF VARCHAR(25) NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(200) NOT NULL,
CARACTERISTICAS VARCHAR(200) NOT NULL
);